name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge Bot
        # You may pin to the exact commit or the version.
        # uses: casassg/auto-merge-bot@8f9d4eef86461f8f102f7bc3ba53c1359201fb18
        uses: casassg/auto-merge-bot@v0.3.2
        with:
          merge_method: 'merge'
          
