
name: Auto Merge PR

on:
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

jobs:
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Merginator 2
        uses: managedkaos/merge-pull-request@v2.0.2
